// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: article.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPC_RESULT int32

const (
	RPC_RESULT_RESULT_FAIL    RPC_RESULT = 0 //失败
	RPC_RESULT_RESULT_SUCCESS RPC_RESULT = 1 //成功
)

// Enum value maps for RPC_RESULT.
var (
	RPC_RESULT_name = map[int32]string{
		0: "RESULT_FAIL",
		1: "RESULT_SUCCESS",
	}
	RPC_RESULT_value = map[string]int32{
		"RESULT_FAIL":    0,
		"RESULT_SUCCESS": 1,
	}
)

func (x RPC_RESULT) Enum() *RPC_RESULT {
	p := new(RPC_RESULT)
	*p = x
	return p
}

func (x RPC_RESULT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPC_RESULT) Descriptor() protoreflect.EnumDescriptor {
	return file_article_proto_enumTypes[0].Descriptor()
}

func (RPC_RESULT) Type() protoreflect.EnumType {
	return &file_article_proto_enumTypes[0]
}

func (x RPC_RESULT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPC_RESULT.Descriptor instead.
func (RPC_RESULT) EnumDescriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

type ARTICLE_SORT int32

const (
	ARTICLE_SORT_ORDER_BY_TIME  ARTICLE_SORT = 0 //最新时间
	ARTICLE_SORT_ORDER_BY_CLICK ARTICLE_SORT = 1 //点击次数
)

// Enum value maps for ARTICLE_SORT.
var (
	ARTICLE_SORT_name = map[int32]string{
		0: "ORDER_BY_TIME",
		1: "ORDER_BY_CLICK",
	}
	ARTICLE_SORT_value = map[string]int32{
		"ORDER_BY_TIME":  0,
		"ORDER_BY_CLICK": 1,
	}
)

func (x ARTICLE_SORT) Enum() *ARTICLE_SORT {
	p := new(ARTICLE_SORT)
	*p = x
	return p
}

func (x ARTICLE_SORT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ARTICLE_SORT) Descriptor() protoreflect.EnumDescriptor {
	return file_article_proto_enumTypes[1].Descriptor()
}

func (ARTICLE_SORT) Type() protoreflect.EnumType {
	return &file_article_proto_enumTypes[1]
}

func (x ARTICLE_SORT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ARTICLE_SORT.Descriptor instead.
func (ARTICLE_SORT) EnumDescriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

type ArticleStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           //文章id
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`      //标题
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`  //内容
	Viewnum       uint32                 `protobuf:"varint,4,opt,name=viewnum,proto3" json:"viewnum,omitempty"` //点击次数
	Time          uint32                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`       //发布时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleStruct) Reset() {
	*x = ArticleStruct{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleStruct) ProtoMessage() {}

func (x *ArticleStruct) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleStruct.ProtoReflect.Descriptor instead.
func (*ArticleStruct) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleStruct) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleStruct) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleStruct) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ArticleStruct) GetViewnum() uint32 {
	if x != nil {
		return x.Viewnum
	}
	return 0
}

func (x *ArticleStruct) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ArticleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          ARTICLE_SORT           `protobuf:"varint,1,opt,name=sort,proto3,enum=article.ARTICLE_SORT" json:"sort,omitempty"` //排序方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListRequest) Reset() {
	*x = ArticleListRequest{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListRequest) ProtoMessage() {}

func (x *ArticleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListRequest.ProtoReflect.Descriptor instead.
func (*ArticleListRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleListRequest) GetSort() ARTICLE_SORT {
	if x != nil {
		return x.Sort
	}
	return ARTICLE_SORT_ORDER_BY_TIME
}

type ArticleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          RPC_RESULT             `protobuf:"varint,1,opt,name=code,proto3,enum=article.RPC_RESULT" json:"code,omitempty"` //调用结果
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                            //错误消息
	List          []*ArticleStruct       `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`                          //列表数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListResponse) Reset() {
	*x = ArticleListResponse{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListResponse) ProtoMessage() {}

func (x *ArticleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListResponse.ProtoReflect.Descriptor instead.
func (*ArticleListResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleListResponse) GetCode() RPC_RESULT {
	if x != nil {
		return x.Code
	}
	return RPC_RESULT_RESULT_FAIL
}

func (x *ArticleListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ArticleListResponse) GetList() []*ArticleStruct {
	if x != nil {
		return x.List
	}
	return nil
}

var File_article_proto protoreflect.FileDescriptor

var file_article_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x7d, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x65,
	0x77, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x69, 0x65, 0x77,
	0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x12, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c, 0x45, 0x5f, 0x53, 0x4f,
	0x52, 0x54, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x7c, 0x0a, 0x13, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x52, 0x50, 0x43, 0x5f, 0x52, 0x45, 0x53, 0x55,
	0x4c, 0x54, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x2a, 0x31, 0x0a, 0x0a, 0x52, 0x50, 0x43, 0x5f, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x2a, 0x35, 0x0a, 0x0c, 0x41, 0x52, 0x54,
	0x49, 0x43, 0x4c, 0x45, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x5f, 0x42, 0x59, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x42, 0x59, 0x5f, 0x43, 0x4c, 0x49, 0x43, 0x4b, 0x10, 0x01,
	0x32, 0x55, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData = file_article_proto_rawDesc
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_article_proto_rawDescData)
	})
	return file_article_proto_rawDescData
}

var file_article_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_article_proto_goTypes = []any{
	(RPC_RESULT)(0),             // 0: article.RPC_RESULT
	(ARTICLE_SORT)(0),           // 1: article.ARTICLE_SORT
	(*ArticleStruct)(nil),       // 2: article.ArticleStruct
	(*ArticleListRequest)(nil),  // 3: article.ArticleListRequest
	(*ArticleListResponse)(nil), // 4: article.ArticleListResponse
}
var file_article_proto_depIdxs = []int32{
	1, // 0: article.ArticleListRequest.sort:type_name -> article.ARTICLE_SORT
	0, // 1: article.ArticleListResponse.code:type_name -> article.RPC_RESULT
	2, // 2: article.ArticleListResponse.list:type_name -> article.ArticleStruct
	3, // 3: article.Article.ArticleList:input_type -> article.ArticleListRequest
	4, // 4: article.Article.ArticleList:output_type -> article.ArticleListResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_article_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		EnumInfos:         file_article_proto_enumTypes,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_rawDesc = nil
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
